export interface ILayoutElements {
  flowerBlue?: boolean
  starPink?: boolean
  flowerWhite?: boolean
  twoBlueFlowers?: boolean
  twoBlueFlowers2?: boolean
  flowerBlue2?: boolean
  flowerBlue3?: boolean
  flowerBlue4?: boolean
  flowerBlue5?: boolean
  flowerBlue6?: boolean
  flowerBlue7?: boolean
  flowerBlue8?: boolean
  flowerBlue9?: boolean
  flowerBlue10?: boolean
  flowerBlue11?: boolean
  flowerWhite2?: boolean
  flowerWhite3?: boolean
  waves1?: boolean
  waves2?: boolean
  waves3?: boolean
  waves4?: boolean
  waves5?: boolean
  waves6?: boolean
  sun1?: boolean
  sun2?: boolean
  sun3?: boolean
  sun4?: boolean
  sun5?: boolean
  flaming?: boolean
  flaps?: boolean
  sunglasses?: boolean
  ball1?: boolean
  ball2?: boolean
  arrow?: boolean
  arrowMasterclass?: boolean
}
