name: Web

on:
  pull_request:
    paths:
      - "apps/web/**"
      - ".github/workflows/web.yml"
  push:
    branches:
      - master
    paths:
      - "apps/web/**"
      - ".github/workflows/web.yml"

jobs:
  web:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/web
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: corepack enable
      - run: yarn install --immutable
      - run: yarn lint
      - run: yarn test:schema
      - run: yarn build
